wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_obs:
  desc: null
  value: "[[0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1.\n\
    \  0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1.\n \
    \ 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1.]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7f191484c090>
_n_updates:
  desc: null
  value: 0
_num_timesteps_at_start:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 32800000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    code_path: code/src/gym/stable_solve.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1652139537
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 3
      - 13
      - 16
      - 22
      - 35
      4: 3.7.11
      5: 0.12.11
      8:
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Box([-1.e+12 -1.e+12 -1.e+12 -1.e+12], [1.e+12 1.e+12 1.e+12 1.e+12], (4,),
    float32)
algo:
  desc: null
  value: PPO
batch_size:
  desc: null
  value: 2048
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f190c0dd0e0>
clip_range_vf:
  desc: null
  value: None
device:
  desc: null
  value: cuda
ent_coef:
  desc: null
  value: 0.0
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f190e326550>
env_name:
  desc: null
  value: PccNs-v0
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
eval_env:
  desc: null
  value: None
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: 0.0003
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7f190e2fa7a0>
max_grad_norm:
  desc: null
  value: 0.5
n_envs:
  desc: null
  value: 1
n_epochs:
  desc: null
  value: 10
n_steps:
  desc: null
  value: 8192
normalize_advantage:
  desc: null
  value: 'True'
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: "Box([-1.  1.  0. -1.  1.  0. -1.  1.  0. -1.  1.  0. -1.  1.  0. -1.  1.\
    \  0.\n -1.  1.  0. -1.  1.  0. -1.  1.  0. -1.  1.  0. -1.  1.  0. -1.  1.  0.\n\
    \ -1.  1.  0. -1.  1.  0. -1.  1.  0. -1.  1.  0. -1.  1.  0. -1.  1.  0.\n -1.\
    \  1.  0. -1.  1.  0.], [   10. 10000.  1000.    10. 10000.  1000.    10. 10000.\
    \  1000.    10.\n 10000.  1000.    10. 10000.  1000.    10. 10000.  1000.    10.\
    \ 10000.\n  1000.    10. 10000.  1000.    10. 10000.  1000.    10. 10000.  1000.\n\
    \    10. 10000.  1000.    10. 10000.  1000.    10. 10000.  1000.    10.\n 10000.\
    \  1000.    10. 10000.  1000.    10. 10000.  1000.    10. 10000.\n  1000.    10.\
    \ 10000.  1000.    10. 10000.  1000.    10. 10000.  1000.], (60,), float32)"
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor): MlpExtractor(\n  \
    \  (shared_net): Sequential()\n    (policy_net): Sequential(\n      (0): Linear(in_features=60,\
    \ out_features=32, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=32,\
    \ out_features=16, bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n\
    \      (0): Linear(in_features=60, out_features=32, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=32, out_features=16, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=16, out_features=4, bias=True)\n\
    \  (value_net): Linear(in_features=16, out_features=1, bias=True)\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
  desc: null
  value: '{''net_arch'': [{''pi'': [32, 16], ''vf'': [32, 16]}]}'
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7f190e31b110>
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: None
start_time:
  desc: null
  value: 1652139540.4661298
target_kl:
  desc: null
  value: None
tensorboard_log:
  desc: null
  value: ./log/2022-05-09-19_38_57/runs/2022-05-09-19_38_57
total_timesteps:
  desc: null
  value: 32800000
use_sde:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
vf_coef:
  desc: null
  value: 0.5
